### ISSUE TITLE
Tell me please

### ISSUE THREAD

**Issue by BITNER209** [noahrepublic/Better-UGC-Sniper#1]
my application does not start, what could be the problem? And one more question  "In case that it errors from invalid cookie, manually get your .ROBLOSECURITY and place it in "cookie.txt" " but there is no Cookie.txt file in the archive. sorry for the stupid question

**Comment by noahrepublic** [comment]
Sorry! my bad actually! Forgot to update that error! Try the new version and run "run.bat" after you installed python. Join the discord for help! discord.gg/Kk8n2QpFCb
